// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oadhnsuutvdkwgnluwlj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hZGhuc3V1dHZka3dnbmx1d2xqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwOTc1MDUsImV4cCI6MjA2NjY3MzUwNX0.ZuP65_LRTL3ADgkHRr3kNtJc2C6j_SdgndSuRVvg_yI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);